### PR TITLE
Nuxtification

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
Opening this as it's almost done, and is 100% better than the current site

### CODE REVIEW

**Comment by ghost** [comment]
@VFDan pls review

**Comment by ghost** [comment]
@GrahamSH-LLK vfdan requested you to update the branch to be up-to-date with the gitpod

**Comment by GrahamSH-LLK** [comment]
Anything on the Gitpod is gone if it wasn't pushed, they auto-discard after being unused. @VFDan What were the changes?

**Comment by ghost** [comment]
> Anything on the Gitpod is gone if it wasn't pushed, they auto-discard after being unused. @VFDan What were the changes?

@GrahamSH-LLK hmm you should have pinned the workspace

**Pull request merged**
